channels:
  - bioconda
  - conda-forge
dependencies:
  - fastp==0.23.2
  - multiqc==1.13a
  - bbmap==38.98
  - cat==5.2.3
  - coverm==0.6.1
  - eggnog-mapper==2.1.9
  - gtdbtk==1.7.0
  - kraken2==2.1.2
  - kaiju==1.9.0
  - sourmash==4.4.3
  - maxbin2==2.2.7
  - metabat2==2.12.1
  - seqtk==1.3
  - prodigal==2.6.3
  - quast==5.2.0
  - checkm-genome==1.2.1
  - spades==3.15.3
  - megahit==1.2.9
  - vsearch==2.21.1
  - blobtools==1.1.1
  - mmseqs2==13.45111
  - pandas==1.4.3
  - samtools==1.15.1
  - das_tool==1.1.4
  - prokka==1.13
  - diamond==2.0.15
  - vsearch==2.21.1
  - python==3.10.6
  - numpy==1.23.2
  - scipy==1.9.1
  - bowtie2==2.4.5
  - bwa==0.7.17  
  - bwa-mem2==2.2.1
  - hmmer==3.1b2
